### ISSUE TITLE
Possible to add a countdown?

### ISSUE THREAD

**Issue by padraic7a** [zengargoyle/selfcontrol#6]
If I start the app and set it for say 20 minutes and then click start it closes. 
If I open it again 3 minutes later it still shows the 20 minute value - and the 'start' button is still clickable.

Would it be possible to show that the process is still running - perhaps by greying out the start button, and adding a countdown?

**Comment by zengargoyle** [comment]
Sorry for the delay, I wanted to ponder for a bit and I'm currently limited
to weekends for TUITs.

Reading the question again, that's not quite how it works.  There is no
process that's still running.  Clicking 'Start' causes the blocks to be
enabled and schedules an at(1) job to remove the block at the expiration
time.  When you re-open the app it is expected behavior that it is possible
to re-block a currently active block.

Consider... you block siteA for 4 hours and start working.  2 hours later
you know your not going to be finished in the remaining 2 hours so you
decide to go ahead and re-block siteA for another 4 hours (or longer) to
give yourself time to finish your work.  It would be bad if you couldn't do
that because siteA was currently blocked at the time.

Further... the use cases would become quite complicated.  You block siteA,
then later block siteB, then you try to block siteA, siteB, and siteC...
what happens?  Is it not allowed because siteA and siteB are already
blocked?  Is it allowed because siteC isn't blocked yet?  Does it ignore
siteA, and siteB and only do siteC?

There is (I think) a menu item to show the currently active blocks (you may
need to check guide, you need to add something to /etc/sudoers to allow it
to work properly).

**Comment by padraic7a** [comment]
Hi, that makes sense. I guess I was thinking of it more as a block that acts on a predefined number of sites - rather than as something that would be applied to one site, and then possibly to another. Thanks for coming back to me about it.
